//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData
{
    using System;
    
    public enum AttendTypeEnum : int
    {
        Present = 1,
        Absent = 2,
        Unknown = 3,
        Late = 4
    }
}
