//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData
{
    using System;
    using System.Collections.Generic;
    
    public partial class X_Meeting_Tag
    {
        public int MeetingId { get; set; }
        public int TagId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
