//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    
    public enum dayofweek : int
    {
        Sun = 0,
        Mon = 1,
        Tues = 2,
        Wed = 3,
        Thurs = 4,
        Fri = 5,
        Sat = 6
    }
}
